packages:
  - 'apps/*'
  - 'ios'
  - 'waelio-data-ts'
allowBuilds:
  '@firebase/util': true
  '@nativescript/core': true
  '@parcel/watcher': true
  core-js-pure: true
  electron: true
  esbuild: true
  protobufjs: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@waelio/realdb@0.1.0'
