/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./../core/components/AppDrawer.vue')['default']
    AppHeader: typeof import('./../core/components/AppHeader.vue')['default']
    AppLayout: typeof import('./../core/components/AppLayout.vue')['default']
    BaseIcon: typeof import('./../core/components/BaseIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewContainer: typeof import('./../core/components/ViewContainer.vue')['default']
  }
}
