/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConsentBanner: typeof import('./../components/common/ConsentBanner.vue')['default']
    CursorTrail: typeof import('./../components/common/CursorTrail.vue')['default']
    MiraclesSwitcher: typeof import('./../components/common/MiraclesSwitcher.vue')['default']
    OfflineRecitationManager: typeof import('./../components/quran/OfflineRecitationManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupportAIWidget: typeof import('./../components/common/SupportAIWidget.vue')['default']
    ThreeBackground: typeof import('./../components/common/ThreeBackground.vue')['default']
    UnFlagsCircle: typeof import('./../components/common/UnFlagsCircle.vue')['default']
  }
}
