/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/': RouteRecordInfo<
      '/blog/',
      '/blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/[slug]': RouteRecordInfo<
      '/blog/[slug]',
      '/blog/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/blog/editor': RouteRecordInfo<
      '/blog/editor',
      '/blog/editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chat': RouteRecordInfo<
      '/chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact': RouteRecordInfo<
      '/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/holynames': RouteRecordInfo<
      '/holynames',
      '/holynames',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Home': RouteRecordInfo<
      '/Home',
      '/Home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home copy': RouteRecordInfo<
      '/home copy',
      '/home%20copy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/miracles': RouteRecordInfo<
      '/miracles',
      '/miracles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/preferences': RouteRecordInfo<
      '/preferences',
      '/preferences',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/privacy': RouteRecordInfo<
      '/privacy',
      '/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/quran/': RouteRecordInfo<
      '/quran/',
      '/quran',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/quran/[...lok]': RouteRecordInfo<
      '/quran/[...lok]',
      '/quran/:lok(.*)',
      { lok: ParamValue<true> },
      { lok: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signup': RouteRecordInfo<
      '/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/support': RouteRecordInfo<
      '/support',
      '/support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasbeeh': RouteRecordInfo<
      '/tasbeeh',
      '/tasbeeh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/terms': RouteRecordInfo<
      '/terms',
      '/terms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/views/admin.vue': {
      routes:
        | '/admin'
      views:
        | never
    }
    'src/views/blog/index.vue': {
      routes:
        | '/blog/'
      views:
        | never
    }
    'src/views/blog/[slug].vue': {
      routes:
        | '/blog/[slug]'
      views:
        | never
    }
    'src/views/blog/editor.vue': {
      routes:
        | '/blog/editor'
      views:
        | never
    }
    'src/views/chat.vue': {
      routes:
        | '/chat'
      views:
        | never
    }
    'src/views/contact.vue': {
      routes:
        | '/contact'
      views:
        | never
    }
    'src/views/holynames.vue': {
      routes:
        | '/holynames'
      views:
        | never
    }
    'src/views/Home.vue': {
      routes:
        | '/Home'
      views:
        | never
    }
    'src/views/home copy.vue': {
      routes:
        | '/home copy'
      views:
        | never
    }
    'src/views/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/views/miracles.vue': {
      routes:
        | '/miracles'
      views:
        | never
    }
    'src/views/preferences.vue': {
      routes:
        | '/preferences'
      views:
        | never
    }
    'src/views/privacy.vue': {
      routes:
        | '/privacy'
      views:
        | never
    }
    'src/views/quran/index.vue': {
      routes:
        | '/quran/'
      views:
        | never
    }
    'src/views/quran/[...lok].vue': {
      routes:
        | '/quran/[...lok]'
      views:
        | never
    }
    'src/views/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/views/signup.vue': {
      routes:
        | '/signup'
      views:
        | never
    }
    'src/views/support.vue': {
      routes:
        | '/support'
      views:
        | never
    }
    'src/views/tasbeeh.vue': {
      routes:
        | '/tasbeeh'
      views:
        | never
    }
    'src/views/terms.vue': {
      routes:
        | '/terms'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
