#!/bin/bash
# iOS Debug Console Helper
# This script helps you view the JavaScript console in your iOS app

echo "🔍 iOS Debug Console Options"
echo ""
echo "OPTION 1: Xcode Console (Easiest)"
echo "  1. Open Xcode"
echo "  2. Run your app (▶️)"
echo "  3. Open the debug console (⇧⌘C)"
echo "  4. Look for JavaScript errors (they start with 'ERROR' or 'console.error')"
echo ""
echo "OPTION 2: Safari Web Inspector (Most Detailed)"
echo "  1. On your Mac, open Safari > Settings > Advanced"
echo "  2. Enable 'Show Develop menu in menu bar'"
echo "  3. Connect your iPhone via USB"
echo "  4. Run the app on your device"
echo "  5. In Safari: Develop > [Your iPhone] > [Peace2074]"
echo "  6. Check the Console tab for errors"
echo ""
echo "OPTION 3: Add Debug Alerts (Quick Test)"
echo "  We can add alert() calls to see where the app breaks"
echo ""
echo "What do you see in the console?"
echo ""
echo "Common black screen causes:"
echo "  ❌ Router init error"
echo "  ❌ Missing component import"
echo "  ❌ i18n translation error"
echo "  ❌ Pinia store error"
echo "  ❌ localStorage/indexedDB error"
